server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamjunhyeok/spring-app-config.git
          clone-on-start: true
          username: iamjunhyeok
          password: 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

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka